# Generated by Django 3.2.25 on 2025-09-15 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bowl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id_cafeteria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('capacidad_maxima', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
                ('zona', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('descuento', models.FloatField(default=0.0)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='jugador',
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jugador',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='duracion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='turno',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turno',
            name='falta1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='falta2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='falta3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='frame_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='puntaje_turno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turno',
            name='spare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='strike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='partida',
            name='pista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.pista'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.reserva'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.pista'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='lanzamiento1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turno',
            name='lanzamiento2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turno',
            name='lanzamiento3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turno',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.partida'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorPartida',
            fields=[
                ('id_jugador_partida', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_final', models.IntegerField(default=0)),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowl.jugador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowl.partida')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasJugador',
            fields=[
                ('id_estadistica', models.AutoField(primary_key=True, serialize=False)),
                ('partidas_jugadas', models.IntegerField(default=0)),
                ('promedio_puntaje', models.FloatField(default=0.0)),
                ('total_strikes', models.IntegerField(default=0)),
                ('total_spares', models.IntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowl.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowl.cliente')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowl.menu')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowl.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='cafeteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.cafeteria'),
        ),
        migrations.AddField(
            model_name='pista',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.estado'),
        ),
        migrations.AddField(
            model_name='pista',
            name='tipo_pista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.tipopista'),
        ),
        migrations.AddField(
            model_name='turno',
            name='jugador_partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.jugadorpartida'),
        ),
    ]
