# Generated by Django 5.2.7 on 2025-10-26 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='email',
        ),
        migrations.AddField(
            model_name='jugador',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.cliente'),
        ),
        migrations.AddField(
            model_name='partida',
            name='jugador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bowl.jugador'),
        ),
        migrations.AddField(
            model_name='partida',
            name='puntaje_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pista',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
