# Generated by Django 5.2.7 on 2025-10-27 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='falta1',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='falta2',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='falta3',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='frame_final',
        ),
        migrations.AddField(
            model_name='jugador',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.partida'),
        ),
        migrations.AddField(
            model_name='partida',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.cliente'),
        ),
        migrations.AddField(
            model_name='partida',
            name='puntaje_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pista',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
        migrations.CreateModel(
            name='PuntajeJugador',
            fields=[
                ('id_puntaje', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField()),
                ('set', models.IntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowl.jugador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowl.partida')),
            ],
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
