# Generated by Django 5.2.7 on 2025-12-01 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntajeJugador',
            fields=[
                ('id_puntaje', models.AutoField(primary_key=True, serialize=False)),
                ('set', models.PositiveSmallIntegerField()),
                ('puntaje', models.PositiveSmallIntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowl.jugador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowl.partida')),
            ],
            options={
                'verbose_name': 'Puntaje por set',
                'verbose_name_plural': 'Puntajes por set',
                'unique_together': {('partida', 'jugador', 'set')},
            },
        ),
    ]
