# Generated by Django 3.2.25 on 2025-09-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0002_auto_20250915_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
    ]
