# Generated by Django 5.2.7 on 2025-10-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0002_remove_jugador_edad_remove_jugador_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='jugador',
        ),
    ]
