# Generated by Django 3.2.25 on 2025-10-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0002_perfilusuario_usuario_reserva_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pista',
            name='numero',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
