# Generated by Django 3.2.25 on 2025-10-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0002_perfilusuario_usuario_pista_numero_reserva_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='falta1',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='falta2',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='falta3',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='frame_final',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
