# Generated by Django 3.2.25 on 2025-09-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0003_remove_cliente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='comida',
            fields=[
                ('id_comida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cafeteria',
            name='ubicacion',
        ),
    ]
