# Generated by Django 5.2.7 on 2025-10-27 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0003_remove_partida_jugador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='cliente',
        ),
        migrations.AddField(
            model_name='jugador',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.partida'),
        ),
        migrations.AddField(
            model_name='partida',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bowl.cliente'),
        ),
        migrations.CreateModel(
            name='PuntajeJugador',
            fields=[
                ('id_puntaje', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField()),
                ('set', models.IntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowl.jugador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bowl.partida')),
            ],
        ),
    ]
