# Generated by Django 3.2.25 on 2025-09-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0004_auto_20250922_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
    ]
