# Generated by Django 3.2.25 on 2025-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0006_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
