# Generated by Django 3.2.25 on 2025-10-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowl', '0007_mensaje'),
        ('bowl', '0007_usuario_contraseña'),
    ]

    operations = [
    ]
