"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

Documentación:
- General: https://docs.djangoproject.com/en/5.2/topics/settings/
- Todos los settings: https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# -------------------------
# BASE_DIR: ruta base del proyecto
# -------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------
# Seguridad y Debug
# -------------------------
SECRET_KEY = 'django-insecure-x**ed=cb%*q+6o(21kz9*nje5x!1kau=n4211=&r*a!$h*-%ss'
DEBUG = True  # En producción debe ser False
ALLOWED_HOSTS = []  # Dominios permitidos para producción


# -------------------------
# Aplicaciones instaladas
# -------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth', 
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bowl',  # ← AGREGA ESTA LÍNEA
]


# -------------------------
# Archivos estáticos
# -------------------------
STATIC_URL = '/static/'  # URL pública de los archivos estáticos
STATICFILES_DIRS = [BASE_DIR / "static"]  # Carpeta donde están los CSS, JS, imágenes


# -------------------------
# Middleware
# -------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # Maneja sesiones
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',             # Protege contra CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Autenticación
    'django.contrib.messages.middleware.MessageMiddleware',     # Mensajes flash
    'django.middleware.clickjacking.XFrameOptionsMiddleware',   # Seguridad clickjacking
]


# -------------------------
# URL y templates
# -------------------------
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Se pueden agregar directorios extra de templates aquí
        'APP_DIRS': True,  # Busca templates en cada app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # Acceso a request en templates
                'django.contrib.auth.context_processors.auth', # Datos de usuario autenticado
                'django.contrib.messages.context_processors.messages', # Mensajes
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# -------------------------
# Base de datos (SQLite)
# -------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Motor SQLite
        'NAME': BASE_DIR / 'db.sqlite3',        # Archivo de base de datos
    }
}


# -------------------------
# Validación de contraseñas
# -------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# -------------------------
# Internacionalización
# -------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# -------------------------
# Archivos estáticos
# -------------------------
STATIC_URL = 'static/'


# -------------------------
# Primary Key por defecto
# -------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# -------------------------
# URLs de login/logout
# -------------------------
LOGIN_URL = '/iniciar_sesion/'         # Redirige si no está logueado
LOGIN_REDIRECT_URL = 'inicio'          # Tras login exitoso
LOGOUT_REDIRECT_URL = 'inicio'         # Tras logout


# -------------------------
# Modelo de usuario personalizado
# -------------------------
AUTH_USER_MODEL = 'bowl.Usuario'  # Usamos nuestro modelo Usuario en lugar de User


# -------------------------
# Configuración de email (Gmail SMTP)
# -------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'faustinopedonelopez@gmail.com'   # Gmail
EMAIL_HOST_PASSWORD = 'nisbekkfrumydcqs'            # Contraseña de aplicación
DEFAULT_FROM_EMAIL = 'faustinopedonelopez@gmail.com' # Remitente por defecto
